[package]
name = "octopii_with_origin_openraft"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "=1"
bytes = "1.10"
futures = "0.3"
octopii = { git = "https://github.com/octopii-rs/octopii", rev = "b54c112d7db7ed1195dd4f600b4b786df85c8e7e" }
openraft = { version = "=0.10.0-alpha.29", default-features = false, features = ["serde", "tokio-rt", "type-alias"] }
openraft-multi = "=0.10.0-alpha.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.52.3", features = ["full"] }
tracing = "0.1"
