[workspace]

resolver = "3"

members = [
  "hello_wasmer_example",
  "hello_wasmer_example/risk_rule_v1",
  "hello_wasmer_example/risk_rule_v2",
  "wasmi_example",
  "hot_upgrade",
  "hot_upgrade/risk_rule_v1",
  "hot_upgrade/risk_rule_v2",
  "wasmtime_example",
  "wasmtime_sandbox_limits",
  "wasmtime_tokio",
  "wit_bindgen_example",
  "wasmtime_actor",
  "wasmtime_wasip2_ability",
]
