use gpui_kit::{AnyView, App, Window};

use crate::tabs::*;
pub struct Demo {
  pub slug: &'static str,
  pub title: &'static str,
  pub description: &'static str,
  pub build: fn(&mut Window, &mut App) -> AnyView,
}
fn build<S: ComponentPage>(window: &mut Window, cx: &mut App) -> AnyView {
  S::new_view(window, cx).into()
}
pub const DEMOS: &[Demo] = &[
  Demo {
    slug: "gpui-util",
    title: "gpui-toolkit-gpui-util",
    description: "基础工具：借用与共享、错误日志、作用域清理、计时及类型注册表。",
    build: build::<GpuiUtilTab>,
  },
  Demo {
    slug: "gpui-form",
    title: "gpui-form",
    description: "从 Rust 模型生成表单：字段状态、数据绑定、回填与提交转换。",
    build: build::<GpuiFormTab>,
  },
  Demo {
    slug: "gpui-elements",
    title: "GPUI 元素",
    description: "参考 Zed GPUI examples：认识 div 之外的原生元素、用途与组合方式。",
    build: build::<GpuiElementsTab>,
  },
  Demo {
    slug: "div-lab",
    title: "div() 实验室",
    description: "从方块到控件：交互演示 div 的样式、变形、放大和组合。",
    build: build::<DivLabTab>,
  },
  Demo {
    slug: "accordion",
    title: "Accordion",
    description: "内部基于 collapse 实现的可折叠面板组件。",
    build: build::<AccordionTab>,
  },
  Demo {
    slug: "alert-dialog",
    title: "AlertDialog",
    description: "使用于重要确认场景的模态对话框组件。",
    build: build::<AlertDialogTab>,
  },
  Demo {
    slug: "alert",
    title: "Alert",
    description: "用于吸引用户注意的重要提示组件。",
    build: build::<AlertTab>,
  },
  Demo {
    slug: "attachment",
    title: "Attachment",
    description: "支持上传状态、预览和操作的可组合文件与媒体附件表面。",
    build: build::<AttachmentTab>,
  },
  Demo {
    slug: "avatar",
    title: "Avatar",
    description: "支持图片、姓名首字母和占位图标的头像组件。",
    build: build::<AvatarTab>,
  },
  Demo {
    slug: "badge",
    title: "Badge",
    description: "用于显示未读数、状态点或图标提示的小徽标组件。",
    build: build::<BadgeTab>,
  },
  Demo {
    slug: "bubble",
    title: "Bubble",
    description: "可承载文本、富内容和 reaction 控件的聊天消息表面。",
    build: build::<BubbleTab>,
  },
  Demo {
    slug: "button",
    title: "Button",
    description: "显示一个按钮，或外观表现为按钮的组件。",
    build: build::<ButtonTab>,
  },
  Demo {
    slug: "calendar",
    title: "Calendar",
    description: "用于展示月份、浏览日期和选择单日或区间的灵活日历组件。",
    build: build::<CalendarTab>,
  },
  Demo {
    slug: "carousel",
    title: "Carousel",
    description: "用于浏览相关内容的可组合 Carousel 组件。",
    build: build::<CarouselTab>,
  },
  Demo {
    slug: "chart",
    title: "Chart",
    description: "支持折线图、柱状图、面积图、饼图、雷达图、K 线图和桑基图的数据可视化组件。",
    build: build::<ChartTab>,
  },
  Demo {
    slug: "checkbox",
    title: "Checkbox",
    description: "用于切换选中与未选中状态的复选框组件。",
    build: build::<CheckboxTab>,
  },
  Demo {
    slug: "clipboard",
    title: "Clipboard",
    description: "用于复制文本或其它内容到剪贴板的按钮组件。",
    build: build::<ClipboardTab>,
  },
  Demo {
    slug: "collapsible",
    title: "Collapsible",
    description: "可展开和收起内容的交互式组件。",
    build: build::<CollapsibleTab>,
  },
  Demo {
    slug: "color-picker",
    title: "ColorPicker",
    description: "支持多种颜色格式、预设色和透明通道的颜色选择组件。",
    build: build::<ColorPickerTab>,
  },
  Demo {
    slug: "combobox",
    title: "Combobox",
    description: "带有可搜索下拉列表的自动补全输入组件。",
    build: build::<ComboboxTab>,
  },
  Demo {
    slug: "command",
    title: "Command",
    description: "命令面板 —— 经过过滤的命令与快捷操作列表。",
    build: build::<CommandTab>,
  },
  Demo {
    slug: "data-table",
    title: "DataTable",
    description: "支持虚拟滚动、排序、筛选和列管理的高性能数据表格。",
    build: build::<DataTableTab>,
  },
  Demo {
    slug: "date-picker",
    title: "DatePicker",
    description: "支持单日期和日期范围选择的日历选择器组件。",
    build: build::<DatePickerTab>,
  },
  Demo {
    slug: "description-list",
    title: "DescriptionList",
    description: "用于以整齐布局展示键值对详情信息的组件。",
    build: build::<DescriptionListTab>,
  },
  Demo {
    slug: "dialog",
    title: "Dialog",
    description: "在应用内容上方显示浮层内容的对话框组件。",
    build: build::<DialogTab>,
  },
  Demo {
    slug: "dock",
    title: "Dock",
    description: "支持标签页、分割面板、边缘 Dock 与状态持久化的生产级工作区布局。",
    build: build::<DockTab>,
  },
  Demo {
    slug: "dropdown_button",
    title: "DropdownButton",
    description: "DropdownButton 由一个主按钮和一个触发下拉菜单的按钮组合而成。",
    build: build::<DropdownButtonTab>,
  },
  Demo {
    slug: "editor",
    title: "Editor",
    description: "支持语法高亮、行号、折叠和文本装饰的源代码编辑器。",
    build: build::<EditorTab>,
  },
  Demo {
    slug: "empty",
    title: "Empty",
    description: "用媒体、文字、操作和自定义内容组合空状态。",
    build: build::<EmptyTab>,
  },
  Demo {
    slug: "focus-trap",
    title: "Focus Trap",
    description: "将键盘焦点限制在指定容器内的工具元素。",
    build: build::<FocusTrapTab>,
  },
  Demo {
    slug: "form",
    title: "Form",
    description: "支持字段布局、校验和多列排布的灵活表单容器。",
    build: build::<FormTab>,
  },
  Demo {
    slug: "group-box",
    title: "GroupBox",
    description: "带可选标题的分组容器组件，用于组织相关内容。",
    build: build::<GroupBoxTab>,
  },
  Demo {
    slug: "hover-card",
    title: "HoverCard",
    description: "鼠标悬停时显示富内容浮层的组件。",
    build: build::<HoverCardTab>,
  },
  Demo {
    slug: "icon",
    title: "Icon",
    description: "以不同尺寸、颜色和变换方式显示 SVG 图标。",
    build: build::<IconTab>,
  },
  Demo {
    slug: "image",
    title: "Image",
    description: "支持加载状态、回退内容和响应式尺寸的灵活图片展示组件。",
    build: build::<ImageTab>,
  },
  Demo {
    slug: "input-group",
    title: "Input Group",
    description: "将输入框、文本域与文本、图标、按钮和工具栏组合使用。",
    build: build::<InputGroupTab>,
  },
  Demo {
    slug: "input",
    title: "Input",
    description: "带校验、掩码和多种扩展能力的文本输入组件。",
    build: build::<InputTab>,
  },
  Demo {
    slug: "kbd",
    title: "Kbd",
    description: "以符合平台习惯的方式显示键盘快捷键。",
    build: build::<KbdTab>,
  },
  Demo {
    slug: "label",
    title: "Label",
    description: "支持高亮、次要文本和样式定制的文本标签组件。",
    build: build::<LabelTab>,
  },
  Demo {
    slug: "list",
    title: "List",
    description: "支持分组、搜索、选择和无限滚动的灵活列表组件。",
    build: build::<ListTab>,
  },
  Demo {
    slug: "marker",
    title: "Marker",
    description: "用于会话状态、通知边界和分隔标记的紧凑组合行。",
    build: build::<MarkerTab>,
  },
  Demo {
    slug: "menu",
    title: "Menu",
    description: "支持图标、快捷键、子菜单和多种菜单项类型的上下文菜单与弹出菜单。",
    build: build::<MenuTab>,
  },
  Demo {
    slug: "message-scroller",
    title: "MessageScroller",
    description: "支持尾部跟随、未读定位和稳定 prepend 的虚拟消息列表。",
    build: build::<MessageScrollerTab>,
  },
  Demo {
    slug: "message",
    title: "Message",
    description: "将发送者身份、元信息、富内容和操作组合成对齐的聊天消息。",
    build: build::<MessageTab>,
  },
  Demo {
    slug: "notification",
    title: "Notification",
    description: "在窗口右上角显示支持自动消失的 toast 通知。",
    build: build::<NotificationTab>,
  },
  Demo {
    slug: "number-input",
    title: "NumberInput",
    description: "带增减按钮与数字格式化能力的数值输入组件。",
    build: build::<NumberInputTab>,
  },
  Demo {
    slug: "otp-input",
    title: "OtpInput",
    description: "带多输入框、自动聚焦和粘贴处理的一次性验证码输入组件。",
    build: build::<OtpInputTab>,
  },
  Demo {
    slug: "pagination",
    title: "Pagination",
    description: "提供页码、上一页和下一页导航的分页组件。",
    build: build::<PaginationTab>,
  },
  Demo {
    slug: "plot",
    title: "Plot",
    description: "用于构建自定义图表和数据可视化的底层绘图库。",
    build: build::<PlotTab>,
  },
  Demo {
    slug: "popover",
    title: "Popover",
    description: "相对于触发元素显示富内容的浮动层组件。",
    build: build::<PopoverTab>,
  },
  Demo {
    slug: "progress",
    title: "Progress",
    description: "用于显示任务完成进度的线性或环形指示器。",
    build: build::<ProgressTab>,
  },
  Demo {
    slug: "questionnaire",
    title: "Questionnaire",
    description: "支持单选、多选、自由输入、校验和导航的可组合多步骤问卷。",
    build: build::<QuestionnaireTab>,
  },
  Demo {
    slug: "radio",
    title: "Radio",
    description: "一组互斥的单选按钮，同一时间只能选中一个选项。",
    build: build::<RadioTab>,
  },
  Demo {
    slug: "rating",
    title: "Rating",
    description: "简单的交互式星级评分组件。",
    build: build::<RatingTab>,
  },
  Demo {
    slug: "resizable",
    title: "Resizable",
    description: "具有拖拽分隔条与尺寸约束的可调整面板布局系统。",
    build: build::<ResizableTab>,
  },
  Demo {
    slug: "root",
    title: "Root View",
    description: "使用 Root 视图为窗口启用主题、通知、对话框及其他 GPUI Component 功能。",
    build: build::<RootDemoTab>,
  },
  Demo {
    slug: "scrollable",
    title: "Scrollable",
    description: "支持自定义滚动条、滚动跟踪与虚拟列表的可滚动容器。",
    build: build::<ScrollbarTab>,
  },
  Demo {
    slug: "select",
    title: "Select",
    description: "通过按钮触发的选项选择组件。",
    build: build::<SelectTab>,
  },
  Demo {
    slug: "settings",
    title: "Settings",
    description: "用于构建设置页、设置分组和设置项的界面组件。",
    build: build::<SettingsTab>,
  },
  Demo {
    slug: "sheet",
    title: "Sheet",
    description: "从屏幕边缘滑出的内容面板组件。",
    build: build::<SheetTab>,
  },
  Demo {
    slug: "shimmer",
    title: "Shimmer",
    description: "可复用、遵循主题和 reduced motion 的文字 loading 高光。",
    build: build::<ShimmerTab>,
  },
  Demo {
    slug: "sidebar",
    title: "Sidebar",
    description: "一个可组合、可主题化、可自定义的侧边栏组件。",
    build: build::<SidebarTab>,
  },
  Demo {
    slug: "skeleton",
    title: "Skeleton",
    description: "在内容加载时显示占位骨架。",
    build: build::<SkeletonTab>,
  },
  Demo {
    slug: "slider",
    title: "Slider",
    description: "通过拖动滑块在区间内选择数值的控件。",
    build: build::<SliderTab>,
  },
  Demo {
    slug: "spinner",
    title: "Spinner",
    description: "显示旋转加载动画，用于反馈任务或异步操作的进行中状态。",
    build: build::<SpinnerTab>,
  },
  Demo {
    slug: "status-bar",
    title: "StatusBar",
    description: "一个分为左、中、右三个区域的水平状态栏，通常放置在窗口或面板底部。",
    build: build::<StatusBarTab>,
  },
  Demo {
    slug: "stepper",
    title: "Stepper",
    description: "用于引导用户按步骤完成流程的进度组件。",
    build: build::<StepperTab>,
  },
  Demo {
    slug: "switch",
    title: "Switch",
    description: "用于在选中和未选中之间切换的开关控件。",
    build: build::<SwitchTab>,
  },
  Demo {
    slug: "table",
    title: "Table",
    description: "一个用于直接渲染表格数据的基础表格组件。",
    build: build::<TableTab>,
  },
  Demo {
    slug: "tabs",
    title: "Tabs",
    description: "将内容拆分为多个标签面板并逐个切换显示的组件。",
    build: build::<TabsTab>,
  },
  Demo {
    slug: "tag",
    title: "Tag",
    description: "用于分类、标记和显示元数据的紧凑标签组件。",
    build: build::<TagTab>,
  },
  Demo {
    slug: "text-view",
    title: "TextView",
    description: "渲染 Markdown 与 HTML 文本，并支持自定义 Markdown 插件。",
    build: build::<TextViewTab>,
  },
  Demo {
    slug: "textarea",
    title: "Textarea",
    description: "支持固定行数、软换行和自动增高的多行文本输入组件。",
    build: build::<TextareaTab>,
  },
  Demo {
    slug: "theme",
    title: "Theme",
    description: "使用 GPUI Component 主题系统定制颜色、字体、圆角以及明暗外观。",
    build: build::<ThemeColorsTab>,
  },
  Demo {
    slug: "title-bar",
    title: "TitleBar",
    description: "支持窗口控制和自定义内容的自定义标题栏组件。",
    build: build::<TitleBarTab>,
  },
  Demo {
    slug: "toggle",
    title: "Toggle",
    description: "以按钮形态表示开关或选中状态的切换组件。",
    build: build::<ToggleTab>,
  },
  Demo {
    slug: "tooltip",
    title: "Tooltip",
    description: "在悬停或聚焦时显示提示信息，支持快捷键和自定义内容。",
    build: build::<TooltipTab>,
  },
  Demo {
    slug: "tree",
    title: "Tree",
    description: "用于显示和导航树形结构数据的层级树组件。",
    build: build::<TreeTab>,
  },
  Demo {
    slug: "virtual-list",
    title: "VirtualList",
    description: "用于大数据集渲染的高性能虚拟列表组件，支持可变尺寸项。",
    build: build::<VirtualListTab>,
  },
];
