use alloy::providers::Provider;
use eyre::Result;

pub mod account;
pub mod account_error;
pub mod array;
pub mod array_remove_by_shifting;
pub mod array_replace_from_end;
pub mod callback;
pub mod constants;
pub mod counter;
pub mod data_locations;
pub mod enum_basic;
pub mod enum_declaration_example;
pub mod enum_import;
pub mod ether_units;
pub mod event_basic;
pub mod event_driven_architecture;
pub mod event_subscription;
pub mod examples;
pub mod function_contract;
pub mod function_modifier;
pub mod gas;
pub mod if_else;
pub mod immutable;
pub mod loop_contract;
pub mod malicious_callback;
pub mod mapping;
pub mod nested_mapping;
pub mod primitives;
pub mod reentrancy_guard;
pub mod reentrancy_guard_transient;
pub mod simple_storage;
pub mod struct_import_example;
pub mod test_storage;
pub mod test_transient_storage;
pub mod todos_struct_declaration;
pub mod todos_structs;
pub mod variables;
pub mod view_and_pure;
pub mod xyz;

pub async fn run_all(provider: &impl Provider) -> Result<()> {
  account_error::run(provider).await?;
  array::run(provider).await?;
  array_remove_by_shifting::run(provider).await?;
  array_replace_from_end::run(provider).await?;
  constants::run(provider).await?;
  counter::run(provider).await?;
  data_locations::run(provider).await?;
  primitives::run(provider).await?;
  enum_basic::run(provider).await?;
  enum_declaration_example::run(provider).await?;
  enum_import::run(provider).await?;
  account::run(provider).await?;
  ether_units::run(provider).await?;
  event_basic::run(provider).await?;
  event_driven_architecture::run(provider).await?;
  event_subscription::run(provider).await?;
  function_contract::run(provider).await?;
  xyz::run(provider).await?;
  function_modifier::run(provider).await?;
  gas::run(provider).await?;
  if_else::run(provider).await?;
  immutable::run(provider).await?;
  loop_contract::run(provider).await?;
  mapping::run(provider).await?;
  nested_mapping::run(provider).await?;
  simple_storage::run(provider).await?;
  variables::run(provider).await?;
  todos_struct_declaration::run(provider).await?;
  struct_import_example::run(provider).await?;
  todos_structs::run(provider).await?;
  callback::run(provider).await?;
  test_storage::run(provider).await?;
  test_transient_storage::run(provider).await?;
  malicious_callback::run(provider).await?;
  reentrancy_guard::run(provider).await?;
  reentrancy_guard_transient::run(provider).await?;
  examples::run(provider).await?;
  view_and_pure::run(provider).await?;
  Ok(())
}
