[package]
name = "tokio_cron_scheduler_example"
version = "0.1.0"
edition = "2024"

[features]
signal = ["tokio/signal"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.104"
chrono = "0.4.45"
chrono-tz = "0.10"
log = "0.4.33"
tokio = { version = "1.53.1", features = ["full"] }
tokio-cron-scheduler = { version = "0.15.1", features = ["signal"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
uuid = "1.24.0"
