[package]
name = "libp2p_kad_b_example"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = "2.4.2"
anyhow = "1.0.104"
futures = "0.3.34"
hex = "0.4.3"
libp2p = { version = "0.57.0", features = [
  "full",
] }
secp256k1 = { version = "0.33.1", features = [
  "alloc",
  "std",
  "rand",
  "serde",
] }
tokio = { version = "1.53.1", features = ["full"] }
