[package]
name = "axum_streams_csv_example"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
axum-streams = { version = "0.29.0", features = ["json", "protobuf", "csv", "arrow", "text"] }
futures = "0.3.34"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["full"] }
tokio-stream = { version = "0.1.19", features = ["full"] }
