[package]
name = "primitive_data_types"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "2.4.1", features = ["contract", "full", "node-bindings", "providers"] }
eyre = "0.6.14"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tokio = { version = "1.53.1", features = ["full"] }
