[workspace]

resolver = "3"

members = [
    "bigdecimal_basic_example",
    "bigdecimal_serde_json_example",
    "sqlx_alloy_u256_example",
    "sqlx_bigdecimal_example",
    "sqlx_chrono_compare_example",
    "sqlx_multi_sql_acquire_example",
    "sqlx_multi_sql_transaction_example",
    "sqlx_rust_decimal_example",
    # "doris_example",
    "sqlx_sqlite_example",
    "sqlx_track_caller_example",
    "sqlx_u256_bigdecimal_example",
    "timescaledb_example",
    "u256_bigdecimal_example",
]
