[package]
name = "game_client"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
avian3d.workspace = true
bevy = { workspace = true, features = ["3d", "ui"] }
bevy_animation_graph.workspace = true
bevy_hanabi.workspace = true
prost.workspace = true
tokio.workspace = true
lightyear = { workspace = true, features = ["std", "client", "udp", "netcode"] }
serde.workspace = true

[build-dependencies]
prost-build.workspace = true
