[package]
name = "wasmtime_wasip2_ability"
version = "0.1.0"
edition = "2024"

[features]
default = ["lsp"]
lsp = []

[dependencies]
anyhow = "1.0.103"
wstd = { version = "0.6.7", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
wasmtime = { version = "46.0.1", features = ["component-model", "async"] }
wasmtime-wasi = "46.0.1"
wasmtime-wasi-http = "46.0.1"
