[package]
name = "axum_prost_post_echo_example"
version = "0.1.0"
edition = "2024"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.8.9"
bytes = "1.12.1"
prost = "0.14.4"
tokio = { version = "1.53.1", features = ["full"] }
tower-http = "0.7.0"

[build-dependencies]
prost-build = "0.14.4"
