[package]
name = "rmpc_qdrant_server_example"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
qdrant-client = "1.19"
reqwest = { version = "0.13", features = ["json"] }
rmcp = { version = "3.4.0", features = ["server", "client", "transport-io"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "io-util", "time"] }
