[package]
name = "reqwest_prost_client_example"
version = "0.1.0"
edition = "2024"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.14.4"
prost-types = "0.14.4"
reqwest = { version = "0.13", features = ["blocking"] }
tokio = { version = "1.53.1", features = ["full"] }

[build-dependencies]
prost-build = "0.14.4"
