[package]
name = "rmcp_example"
version = "0.1.0"
edition = "2024"

[dependencies]
rmcp = { version = "3.4.0", features = ["client", "transport-io"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "io-util"] }
