[package]
name = "raft_kv_memstore_grpc"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "=2"
clap = { version = "4.6.6", features = ["derive", "env"] }
dashmap = "6.2.1"
futures = "0.3.33"
log-mem = { path = "../log-mem", features = [] }
mem-log = { path = "../mem-log" }
openraft = { version = "0.10.0-alpha.33", default-features = false, features = [
  "type-alias",
] }
prost = "0.14.4"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
tonic = "0.14.6"
tonic-prost = "0.14.6"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[build-dependencies]
prost-build = "0.14.4"
tonic-prost-build = "0.14.6"
