[package]
name = "game_server"
version = "0.1.0"
edition = "2024"

[dependencies]
agones.workspace = true
anyhow.workspace = true
avian3d.workspace = true
bevior_tree.workspace = true
bevy = { workspace = true, features = ["bevy_log", "bevy_state", "std"] }
bevy_animation_graph = { workspace = true, optional = true }
bevy_ecs.workspace = true
bevy_hanabi = { workspace = true, optional = true }
bevy_replicon.workspace = true
lightyear = { workspace = true, features = ["std", "client", "server", "udp", "netcode", "replication"] }
prost.workspace = true
serde.workspace = true
tokio.workspace = true

[features]
default = []
visual-effects = ["dep:bevy_animation_graph", "dep:bevy_hanabi"]

[build-dependencies]
prost-build.workspace = true
