// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MyMessage {
  #[prost(string, tag = "1")]
  pub content: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OtherMessage {
  #[prost(string, tag = "1")]
  pub data: ::prost::alloc::string::String,
}
