[package]
name = "encrypt-file-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[workspace]
members = ["."]

[dependencies]
libfuzzer-sys = "0.4"
encrypt_file = { path = ".." }
aws-lc-rs = "1.18.1"
zeroize = "1.9.0"

[[bin]]
name = "decrypt"
path = "fuzz_targets/decrypt.rs"
test = false
doc = false
bench = false
