// This file is @generated by prost-build.
pub mod counter_number {
  include!("counter_number.rs");
}
pub mod deeper_resource {
  include!("deeper_resource.rs");
}
pub mod mandelbrot {
  include!("mandelbrot.rs");
}
pub mod mypackage {
  include!("mypackage.rs");
}
pub mod sample_resource {
  include!("sample_resource.rs");
}
