// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MyMessage {
  #[prost(string, tag = "1")]
  pub content: ::prost::alloc::string::String,
}
impl ::prost::Name for MyMessage {
  const NAME: &'static str = "MyMessage";
  const PACKAGE: &'static str = "mypackage";
  fn full_name() -> ::prost::alloc::string::String {
    "mypackage.MyMessage".into()
  }
  fn type_url() -> ::prost::alloc::string::String {
    "/mypackage.MyMessage".into()
  }
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OtherMessage {
  #[prost(string, tag = "1")]
  pub data: ::prost::alloc::string::String,
}
impl ::prost::Name for OtherMessage {
  const NAME: &'static str = "OtherMessage";
  const PACKAGE: &'static str = "mypackage";
  fn full_name() -> ::prost::alloc::string::String {
    "mypackage.OtherMessage".into()
  }
  fn type_url() -> ::prost::alloc::string::String {
    "/mypackage.OtherMessage".into()
  }
}
