// All types (GuestMessage, HostMessage, ActorResponse) are now defined in
// src/wit/actor.wit and generated by wasmtime::component::bindgen! (host) and
// wit_bindgen::generate! (wasm guest).  This file is intentionally empty.
