[package]
name = "libp2p_flutter_webrtc_server_example"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
futures = "0.3.34"
libp2p = { version = "0.57.0", features = [
  "ed25519",
  "macros",
  "request-response",
  "tokio",
] }
libp2p-request-response = { version = "0.30.0", features = ["cbor"] }
libp2p-webrtc = { version = "0.10.0-alpha", features = ["tokio"] }
rand = "0.10.2"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.53.1", features = ["macros", "rt", "signal"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
