import { test, expect } from '@playwright/test';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
const exec = promisify(execFile);
const client = fileURLToPath(new URL('../../../gpui_workspace_example/target/debug/studio-smoke', import.meta.url));
test('new studio route: local TS preview, publish, native sync, draft preservation and recovery', async ({page, baseURL}) => {
  const errors: string[] = [];
  const endpoints: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (new URL(request.url()).pathname.startsWith('/api/')) endpoints.push(new URL(request.url()).pathname); });
  await page.goto('/studio');
  await expect(page.locator('#status')).toContainText('已同步');
  await page.locator('#theme').selectOption('sunset');
  await page.locator('#intensity').fill('35');
  await expect(page.locator('#preview-label')).toHaveText('落日橙 · 强度 35%');
  await expect(page.locator('#preview')).toHaveCSS('background-color', 'rgb(234, 88, 12)');
  await expect(page.locator('#published')).toContainText('海洋蓝 · 强度 70% · 版本 0');
  await page.getByRole('button', {name: '发布到两端'}).click();
  await expect(page.locator('#published')).toHaveText('落日橙 · 强度 35% · 版本 1');
  await exec(client, [], {env: {...process.env, TOPCOAT_URL: baseURL!}, timeout: 30000});
  await expect(page.locator('#published')).toHaveText('森林绿 · 强度 80% · 版本 2');
  await expect(page.locator('#preview-label')).toHaveText('森林绿 · 强度 80%');
  await page.locator('#intensity').fill('20');
  await expect(page.locator('#draft-status')).toContainText('本地预览');
  // A new remote publication must update shared state without destroying the local draft.
  await page.request.post('/api/studio', {data: {action: 'apply', theme: 'ocean', intensity: 90}});
  await expect(page.locator('#published')).toContainText('海洋蓝 · 强度 90% · 版本 3');
  await expect(page.locator('#intensity')).toHaveValue('20');
  await page.getByRole('button', {name: '使用最新发布'}).click();
  await expect(page.locator('#intensity')).toHaveValue('90');
  await page.route('**/api/studio', route => route.fulfill({json: {theme: 'invalid', intensity: 0, revision: 4}}));
  await expect(page.locator('#status')).toContainText('配色响应无效');
  await expect(page.locator('#published')).toContainText('版本 3');
  await page.unroute('**/api/studio');
  await expect(page.locator('#status')).toContainText('已同步');
  expect([...new Set(endpoints)]).toEqual(['/api/studio']);
  expect(errors).toEqual([]);
});
