[package]
name = "raft_kv_memstore"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.8"
clap = { version = "4.6.4", features = ["derive", "env"] }
client-http = { path = "../client-http" }
env_logger = "0.11.11"
futures = "0.3.33"
log-mem = { path = "../log-mem" }
mem-log = { path = "../mem-log" }
network-v2-http = { path = "../network-v2-http" }
openraft = { version = "0.10.0-alpha.33", features = [
  "serde",
  "type-alias",
] }
reqwest = { version = "0.13", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sm-mem = { path = "../sm-mem" }
tokio = { version = "1.53.1", default-features = false, features = [
  "macros",
  "net",
  "rt-multi-thread",
  "sync",
] }
tracing = "0.1.44"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
types-kv = { path = "../types-kv" }
