// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EchoMessage {
  #[prost(string, tag = "1")]
  pub message: ::prost::alloc::string::String,
}
