create table if not exists public.cities (
  id bigint generated by default as identity primary key,
  name text not null unique
);

insert into public.cities (name)
values
  ('Tokyo'),
  ('Osaka'),
  ('Shanghai')
on conflict (name) do nothing;
