[package]
name = "hyper_rustls_server_example"
version = "0.1.0"
edition = "2024"

[dependencies]
http = "1.4.2"
http-body-util = "0.1.4"
hyper = { version = "1.11.0", features = ["full"] }
hyper-util = { version = "0.1.20", features = ["full"] }
rustls = "0.23.42"
rustls-pemfile = "2.2.0"
rustls-pki-types = "1.15.0"
tokio = { version = "1.53.1", features = ["full"] }
tokio-rustls = "0.26.4"

[features]
ring = []
