package a:b;

interface temperature-types {
    record fahrenheit {
        degrees: f32,
    }

    record celsius {
        degrees: f32,
    }

    record temperature-state {
        path: string,
        content-json: string,
    }

    record temperature-result {
        celsius: celsius,
        state: temperature-state,
    }
}

world the-world {
    export temperature-service: interface {
        use temperature-types.{temperature-state, temperature-result};

        calculate-celsius: func(state: temperature-state) -> temperature-result;
    }
}
