use futures::{future, prelude::*};
use std::net::{IpAddr, Ipv4Addr};

use tarpc::{
  context,
  server::{self, incoming::Incoming, Channel},
  tokio_serde::formats::Json,
};

#[tarpc::service]
pub trait HelloWorld {
  async fn hello(name: String) -> String;
}

#[derive(Clone)]
struct HelloWorldImpl;

#[tarpc::server]
impl HelloWorld for HelloWorldImpl {
  async fn hello(self, _: context::Context, name: String) -> String {
    format!("Hello, {}!", name)
  }
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
  let server_addr = (IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1)), 8080);

  let mut listener = tarpc::serde_transport::tcp::listen(&server_addr, Json::default).await?;
  listener.config_mut().max_frame_length(usize::MAX);
  listener
    // Ignore accept errors.
    .filter_map(|r| future::ready(r.ok()))
    .map(server::BaseChannel::with_defaults)
    // Limit channels to 1 per IP.
    .max_channels_per_key(1, |t| t.transport().peer_addr().unwrap().ip())
    // serve is generated by the service attribute. It takes as input any type implementing
    // the generated World trait.
    .map(|channel| {
      let server = HelloWorldImpl;
      channel.execute(server.serve())
    })
    // Max 10 channels.
    .buffer_unordered(10)
    .for_each(|_| async {})
    .await;
  Ok(())
}
