package a:b;

interface temperature-types {
    record fahrenheit {
        degrees: f32,
    }

    record celsius {
        degrees: f32,
    }

    record host-state {
        current-fahrenheit: f32,
        temperature-read-count: u32,
        conversion-count: u32,
        last-fahrenheit: option<f32>,
        last-celsius: option<f32>,
    }

    record temperature-result {
        celsius: celsius,
        state: host-state,
    }
}

world the-world {
    export temperature-service: interface {
        use temperature-types.{host-state, temperature-result};

        calculate-celsius: func(state: host-state) -> temperature-result;
    }
}
