package a:b;

world the-world {
    import thermometer: interface {
        record fahrenheit {
            degrees: f32,
        }

        record celsius {
            degrees: f32,
        }

        what-temperature-is-it: func() -> fahrenheit;
        convert-to-celsius: func(a: fahrenheit) -> celsius;
    }

    export temperature-service: interface {
        record celsius {
            degrees: f32,
        }

        run: func() -> celsius;
    }
}
