[workspace]
resolver = "3"

members = [
  "bevy_ecs_example",
  "bevy_setup_example",
  "bevy_arpg_example",
  "bevy_single_player_example",
  "bevy_quinnet_chat_server_example",
  "bevy_quinnet_chat_client_example",
  "bevy_quinnet_breakout_server_example",
  # "naia-bevy-demo-shared",
  # "bevy_naia_server_example",
  # "bevy_naia_client_example",
  "bevy_ai",
  "game_shared",
  "game_server",
  "game_client",
]

[workspace.dependencies]
agones = "1.59.0"
anyhow = "1.0"
avian3d = { version = "0.7.0", default-features = false, features = ["3d", "f32", "parry-f32"] }
bevior_tree = { version = "0.11.0", default-features = false }
bevy = { version = "0.19.0", default-features = false }
bevy_animation_graph = "0.11"
bevy_ecs = "0.19.0"
bevy_hanabi = { version = "0.19", default-features = false, features = ["3d"] }
bevy_replicon = { version = "0.41.1", default-features = false }
kameo = { version = "0.22.2", features = ["remote"] }
lightyear = { version = "0.28.0", default-features = false }
prost = "0.14.4"
prost-build = "0.14.4"
redis = { version = "1.5.0", default-features = false, features = ["tokio-comp", "connection-manager"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "sync", "time"] }
