[workspace]
resolver = "3"

members = [
  "bevy_ecs_example",
  "bevy_setup_example",
  "bevy_arpg_example",
  "bevy_single_player_example",
  "bevy_quinnet_chat_server_example",
  "bevy_quinnet_chat_client_example",
  "bevy_quinnet_breakout_server_example",
  # "naia-bevy-demo-shared",
  # "bevy_naia_server_example",
  # "bevy_naia_client_example",
  "bevy_ai",
  "game_server",
  "game_client",
]

[workspace.dependencies]
agones = "1.59.0"
anyhow = "1.0"
avian3d = { version = "0.7.0", default-features = false, features = ["3d", "f32", "parry-f32"] }
bevior_tree = { version = "0.11.0", default-features = false }
bevy = { version = "0.19.0", default-features = false }
bevy_animation_graph = {  git = "https://github.com/getong/bevy_animation_graph", branch = "bevy-0.19", default-features = false }
bevy_ecs = "0.19.0"
bevy_hanabi = { version = "0.19", default-features = false, features = ["3d"] }
lightyear = { version = "0.28.0", default-features = false }
prost = "0.14.4"
prost-build = "0.14.4"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread", "sync", "time"] }
