apiVersion: v1
kind: Service
metadata:
  name: bevy-game-server-local
  namespace: default
  labels:
    app.kubernetes.io/name: bevy-game-server
    app.kubernetes.io/component: game-server
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: bevy-game-server
    app.kubernetes.io/component: game-server
  ports:
    - name: game
      protocol: UDP
      port: 6000
      targetPort: 6000
      nodePort: 30600
