[package]
name = "ecdysis_echo"
version = "0.1.0"
edition = "2024"

[features]
default = ["systemd_sockets"]
systemd_notify = ["ecdysis/systemd_notify"]
systemd_sockets = ["ecdysis/systemd_sockets"]

[dependencies]
ecdysis = "1.1.1"
env_logger = "0.11.11"
futures = "0.3.32"
log = "0.4.33"
nix = { version = "0.31.3", features = ["process"] }
tokio = { version = "1.52.3", features = ["full"] }
waitgroup = "0.1.2"
